# Configuration file for the Navigation Manager Node

destinations:
  '1':
    name: 'Destination 1 (Dynamic GPS)'
    source: 'topic'
    topic_name: '/gps/fix'

  '2':
    name: 'Destination 2'
    source: 'recorded'
    gps_coords:
      latitude: 58.641433  # Пример реальных координат
      longitude: 49.623650
    map_name: 'warehouse_map'
    map_target_pose:
      header:
        frame_id: 'map'
      pose:
        position: {x: 5.0, y: 3.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

  '3':
    name: 'Destination 3'
    source: 'recorded'
    gps_coords:
      latitude: 58.641450
      longitude: 49.623700
    map_name: 'office_map'
    map_target_pose:
      header:
        frame_id: 'map'
      pose:
        position: {x: 10.0, y: 7.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

  '4':
    name: 'Destination 4'
    source: 'recorded'
    gps_coords:
      latitude: 58.641400
      longitude: 49.623800
    map_name: 'another_map'
    map_target_pose:
      header:
        frame_id: 'map'
      pose:
        position: {x: 15.0, y: 5.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

base:
  name: 'Base Station'
  source: 'recorded'
  gps_coords:
    latitude: 58.641380
    longitude: 49.623600
  map_name: 'base_map_area'
  map_target_pose:
    header:
      frame_id: 'map'
    pose:
      position: {x: 0.0, y: 0.0, z: 0.0}
      orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}

map_areas:
  'warehouse_map':
    bounds: {min_lat: 58.6413730, max_lat: 58.6414942, min_lon: 49.6234000, max_lon: 49.6239000}
  'office_map':
    bounds: {min_lat: 58.6413730, max_lat: 58.6414942, min_lon: 49.6234000, max_lon: 49.6239000}
  'another_map':
    bounds: {min_lat: 58.6413730, max_lat: 58.6414942, min_lon: 49.6234000, max_lon: 49.6239000}
  'base_map_area':
    bounds: {min_lat: 58.6413730, max_lat: 58.6414942, min_lon: 49.6234000, max_lon: 49.6239000}

time_at_destination_duration: 300.0